name: Deploy JAR

on:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Rename jar
        run: mv target/*.jar target/product-service.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: product-service
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: product-service
          path: ./artifact

      - name: Configure SSH key for ec2 access
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Add ec2 IP to known host list
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

      - name: Set up Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run machine setup playbook
        run: |
          ansible-playbook \
          -i ${{ secrets.EC2_HOST }}, ansible/JAR-setup.yml \
          --user ${{ secrets.EC2_USER }} \
          --private-key ~/.ssh/deploy_key

      - name: Run deploy playbook
        run: |
          ansible-playbook \
          -i ${{ secrets.EC2_HOST }}, ansible/JAR-run.yml \
          --user ${{ secrets.EC2_USER }} \
          --private-key ~/.ssh/deploy_key \
          --extra-vars "artifact_path=$GITHUB_WORKSPACE/artifact app_name=product-service"